# Generated by Django 4.0.2 on 2022-03-11 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_brand_categoryoffer_coupondetail_productoffer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='c_offer',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.categoryoffer'),
        ),
    ]
