# Generated by Django 4.0.2 on 2022-03-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_product_p_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_name',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], default='Home', max_length=20),
        ),
    ]
