# Generated by Django 4.0.2 on 2022-03-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_shippingaddress_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
