# Generated by Django 4.0.2 on 2022-03-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='category_img',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
