# Generated by Django 4.0.2 on 2022-03-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_categorie_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
