# Generated by Django 4.0.2 on 2022-03-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_categoryoffer_name_alter_productoffer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='percent',
            field=models.FloatField(default=1, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='percent',
            field=models.FloatField(default=1, max_length=30, null=True),
        ),
    ]
