# Generated by Django 4.0.2 on 2022-03-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_categoryoffer_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupondetail',
            name='offer_percentage',
            field=models.FloatField(default=1),
        ),
    ]
