# Generated by Django 4.0.2 on 2022-03-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_coupondetail_offer_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupondetail',
            name='exp_date',
            field=models.DateField(null=True),
        ),
    ]
