# Generated by Django 4.0.2 on 2022-03-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_coupondetail_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupondetail',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
