# Generated by Django 4.0.2 on 2022-03-19 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_alter_usecoupon_fororder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecoupon',
            name='fororder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.orderdetail'),
        ),
    ]
