# Generated by Django 4.0.2 on 2022-03-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_alter_usecoupon_fororder'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecoupon',
            name='checking',
            field=models.BooleanField(default=False),
        ),
    ]
