from unicodedata import name
from django.urls import path
from . import views

urlpatterns = [
    path('',views.admin_login,name="admin_login"),
    path('admin_home', views.admin_home, name= "admin_home"),
    path('admin_search', views.admin_search, name= "admin_search"),
    path('admin_logout', views.admin_logout, name= "admin_logout"),
    path('sales_report', views.sales_report, name= "sales_report"),
    path('export_csv', views.export_csv, name= "export_csv"),
    path('export_excel', views.export_excel, name= "export_excel"),
     path('export_pdf', views.export_pdf, name= "export_pdf"),
    path('users_table',views.users_table, name="users_table"),
    path('categories_table',views.categories_table, name="categories_table"),
    path('brand_table',views.brand_table, name="brand_table"),
    path('products_table',views.products_table, name="products_table"),
    path('order_table',views.order_table, name="order_table"),
    path('banner_table',views.banner_table, name="banner_table"),
    path('coupon_table',views.coupon_table, name="coupon_table"),
    path('coupon_add',views.coupon_add, name="coupon_add"),
    path('coupon_usage',views.coupon_usage, name="coupon_usage"),
    path('coupon_status',views.coupon_status, name="coupon_status"),
    path('block_user', views.block_user, name="block_user"),
    path('category_offers', views.category_offers, name="category_offers"),
    path('categories_offers_add',views.categories_offers_add , name="categories_offers_add"),
    path('show_offer_category/<int:id>',views.show_offer_category, name="show_offer_category"),
    path('remove_offer_category',views.remove_offer_category, name="remove_offer_category"),
    path('add_offer_category',views.add_offer_category, name="add_offer_category"),
    path('categories_offer_delete',views.categories_offer_delete , name="categories_offer_delete"),
    path('categories_offer_update/<int:id>',views.categories_offer_update, name="categories_offer_update"),
    path('product_offer_add',views.product_offer_add , name="product_offer_add"),
    path('show_offer_products/<int:id>',views.show_offer_products, name="show_offer_products"),
    path('remove_offer_product',views.remove_offer_product, name="remove_offer_product"),
    path('add_offer_product',views.add_offer_product, name="add_offer_product"),
    path('product_offer_delete',views.product_offer_delete , name="product_offer_delete"),
    path('product_offer_update/<int:id>',views.product_offer_update, name="product_offer_update"),
    path('product_offers', views.product_offers, name="product_offers"),
    path('order_products/<int:id>', views.order_products, name="order_products"),
    path('order_cancel/<int:id>', views.order_cancel, name="order_cancel"),
    path('update_order/<int:id>', views.update_order, name="update_order"),
    path('order_shipped/<int:id>', views.order_shipped, name="order_shipped"),
    path('order_ood/<int:id>', views.order_ood, name="order_ood"),
    path('order_completed/<int:id>', views.order_completed, name="order_completed"),
    path('cancel_req/<int:id>', views.cancel_req, name="cancel_req"),
    path('categories_add',views.categories_add , name="categories_add"),
    path('categories_delete',views.categories_delete , name="categories_delete"),
    path('categories_update/<int:id>',views.categories_update, name="categories_update"),
    path('brand_add',views.brand_add , name="brand_add"),
    path('brand_delete',views.brand_delete , name="brand_delete"),
    path('brand_update/<int:id>',views.brand_update, name="brand_update"),
    path('products_add',views.products_add , name="products_add"),
    path('products_delete',views.products_delete , name="products_delete"),
    path('products_update/<int:id>',views.products_update, name="products_update"),
    path('products_view/<int:id>',views.product_view, name="products_view"),
    path('banner_add',views.banner_add , name="banner_add"),
    path('banner_delete',views.banner_delete , name="banner_delete"),
    path('banner_update/<int:id>',views.banner_update, name="banner_update")


]